version : '3'
services:
  control:
    build:
      context: ./docker/env
    hostname: control
    links:
      - lb01
      - app01
      - app02
      - db01
    ports:
      - "2200:22"
    volumes:
      - ./:/home/work
    tty: true
  lb01:
    build:
      context: ./docker/env
    hostname: lb01
    links:
      - app01
      - app02
    ports:
      - "2201:22"
      - "8001:80"
    tty: true
  app01:
    build:
      context: ./docker/env
    hostname: app01
    links:
      - db01
    ports:
      - "2211:22"
      - "8081:80"
    tty: true
  app02:
    build:
      context: ./docker/env
    hostname: app02
    links:
      - db01
    ports:
      - "2212:22"
      - "8082:80"
    tty: true
  db01:
    build:
      context: ./docker/env
    hostname: db01
    ports:
      - "2222:22"
      - "3306:3306"
    tty: true
